# Generated by Django 4.2.16 on 2024-12-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=50)),
                ('photo_path', models.CharField()),
            ],
        ),
    ]
