# Generated by Django 4.2.16 on 2025-04-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.CharField(max_length=10)),
                ("course_name", models.CharField(max_length=70)),
                (
                    "course_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.teachermodel",
                    ),
                ),
            ],
            options={
                "db_table": "course",
            },
        ),
        migrations.CreateModel(
            name="CourseRegistartionModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendance.coursemodel",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authentication.studentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "course_registration",
            },
        ),
        migrations.CreateModel(
            name="AttendanceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_of_attendance", models.DateTimeField(auto_now=True)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="attendance.coursemodel",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authentication.studentmodel",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
            },
        ),
    ]
