# Generated by Django 4.2.16 on 2025-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancemodel",
            name="session_id",
            field=models.IntegerField(default=0),
        ),
    ]
