# Generated by Django 4.2.16 on 2025-04-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_studentmodel_moodle_id"),
        ("attendance", "0002_attendancemodel_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemodel",
            name="course_id",
            field=models.ForeignKey(
                db_column="course_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="attendance.coursemodel",
            ),
        ),
        migrations.AlterField(
            model_name="attendancemodel",
            name="date_of_attendance",
            field=models.DateTimeField(auto_now=True, db_column="date_of_attendance"),
        ),
        migrations.AlterField(
            model_name="attendancemodel",
            name="session_id",
            field=models.IntegerField(db_column="session_id", default=0),
        ),
        migrations.AlterField(
            model_name="attendancemodel",
            name="student_id",
            field=models.ForeignKey(
                db_column="student_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="authentication.studentmodel",
            ),
        ),
    ]
