# Generated by Django 4.2.16 on 2025-04-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendancemodel_course_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemodel",
            name="course_id",
            field=models.IntegerField(),
        ),
    ]
