# Generated by Django 4.2.16 on 2025-04-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=10, unique=True)),
                ("student_name", models.CharField(max_length=50)),
                ("photo_path", models.CharField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "student",
            },
        ),
        migrations.CreateModel(
            name="TeacherModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.CharField(max_length=10, unique=True)),
                ("teacher_name", models.CharField(max_length=50)),
                ("photo_path", models.CharField()),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "teacher",
            },
        ),
    ]
