# Generated by Django 4.2.16 on 2025-04-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="moodle_id",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
    ]
