# Generated by Django 4.2.16 on 2025-07-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_studentmodel_moodle_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="student_email",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AddField(
            model_name="teachermodel",
            name="moodle_id",
            field=models.CharField(default="", max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name="teachermodel",
            name="teacher_email",
            field=models.CharField(default="", max_length=70),
        ),
    ]
